// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GamingWorldBackEnd.Tests.Publications
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PostPublicationsServiceTestFeature : object, Xunit.IClassFixture<PostPublicationsServiceTestFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PostPublicationsServiceTests.feature"
#line hidden
        
        public PostPublicationsServiceTestFeature(PostPublicationsServiceTestFeature.FixtureData fixtureData, GamingWorldBackEnd_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Publications", "PostPublicationsServiceTest", "As a developer\r\nI want to create a new publication through an API\r\nSo that i dont" +
                    " have to manually create one in the database.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
 #line hidden
#line 7
  testRunner.Given("the endpoint https://localhost:5001/api/v1/publications is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create Publications")]
        [Xunit.TraitAttribute("FeatureTitle", "PostPublicationsServiceTest")]
        [Xunit.TraitAttribute("Description", "Create Publications")]
        [Xunit.TraitAttribute("Category", "Publication_Creation")]
        public virtual void CreatePublications()
        {
            string[] tagsOfScenario = new string[] {
                    "Publication_Creation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create Publications", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 10
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "publicationType",
                            "title",
                            "content",
                            "participantLimit",
                            "prizePool",
                            "tournamentDate",
                            "tournamentHour",
                            "createdAt",
                            "gameId",
                            "userId"});
                table1.AddRow(new string[] {
                            "1",
                            "Example of Publication",
                            "Example of content for a publication test where i reach de minimum characters",
                            "10",
                            "50",
                            "null",
                            "null",
                            "2021-11-06T17:20:14.579Z",
                            "null",
                            "1"});
#line 11
  testRunner.When("a POST Request is sent with body", ((string)(null)), table1, "When ");
#line hidden
#line 14
  testRunner.Then("a Response with Status 200 is received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "publicationType",
                            "title",
                            "content",
                            "participantLimit",
                            "prizePool",
                            "tournamentDate",
                            "tournamentHour",
                            "createdAt",
                            "gameId",
                            "userId"});
                table2.AddRow(new string[] {
                            "1",
                            "1",
                            "Example of Publication",
                            "Example of content for a publication test where i reach de minimum characters",
                            "10",
                            "50",
                            "null",
                            "null",
                            "2021-11-06T17:20:14.579Z",
                            "null",
                            "1"});
#line 15
  testRunner.And("a Publication Resource is included in the response body.", ((string)(null)), table2, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PostPublicationsServiceTestFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PostPublicationsServiceTestFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
